name: Web Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Deploy to Tomcat
      run: curl -v -u ${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }} -T /home/runner/work/GitHubActions-WebAppDeployment/GitHubActions-WebAppDeployment/target/spring3-mvc-maven-xml-hello-world-3.0-SNAPSHOT.war 'http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/deploy?path=/myweb_dev_action&update=true'

    
